# Generated by Django 4.1.3 on 2024-02-03 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="reply",
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="issue",
            field=models.CharField(max_length=300),
        ),
    ]
